CREATE OR REPLACE TRIGGER entrenadortenista
    BEFORE INSERT OR UPDATE 
    ON TENISTAEDICIONENTRENADOR 
    FOR EACH ROW
    
DECLARE num_col int;
BEGIN     
    SELECT COUNT(*) INTO num_col FROM COMPITE WHERE COMPITE.IDEdicion = :new.IDEdicion;
    IF ( num_col != 0) THEN
        RAISE_APPLICATION_ERROR(-20420,'------ ERROR. EL TORNEO YA HA EMPEZADO NO SE PUEDE AÑADIR UN TENISTA A UN ENTRENADOR');    
    END IF ;
END;
